### ISSUE TITLE
Enforce Rotation On Specific Grid Item

### ISSUE THREAD

**Issue by danmarzola** [ShishioValentine/MiqoCrafter#1]
I not highly skilled in C#, but i think this can be solved including encapsulation {} on nodeName

Miqo Documentation:
> {} – perform a skill rotation only for this item.
> For example, if you focus on gathering ‘Dark Chestnut’, you may want to use Blessed Harvest 2 only when it is present in the node.
> In this case, ‘{dark chestnut}’ will prevent Miqobot from wasting GP on anything else.

MiqoCraftCore.cs on LINE 107:

`nodeName = "{"+nodeName +"}\",\"Crystal\",\"Shard";`

Also instead using **rotationifgp** , i think is more effective setting the rotation using **gatherrotation**

For farming Crystal and Shard, i think a default rotation should be active instead using selected

Thx for good work, amazing tool

**Comment by ShishioValentine** [comment]
Hi !

Good idea!
I think you have some code on your side, do you want to integrate it in the master ?

**Comment by danmarzola** [comment]
I will open a pull request so you can check the diff.
