### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by jalsarraf0** [ShishioValentine/MiqoCrafter#15]
Hey there, 

I was wondering if this is still maintained? It's an awesome tool.

**Comment by ShishioValentine** [comment]
Hi !

Well I'm not playing FFXIV a lot lately, but yeah, if there is any issue
I'll look into it !


Le mer. 28 juin 2023 à 16:29, Jamal Al-Sarraf ***@***.***> a
écrit :
